spring.application.name=Quora-Project

spring.datasource.username=root

spring.datasource.password=SQL2026

#To enable SQL logging
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/QUORA_DB_LOCAL

spring.jpa.hibernate.ddl-auto=update